
import { z } from "zod";
import { db } from "@/lib/firebase";
import { ref, push, set, remove, runTransaction } from "firebase/database";
import type { Account } from "./types";
import { getDictionary } from "./i18n/dictionaries";
import { getCountryNameByFlag } from "./country-flags";

const REPORTS_TO_DELETE = 20;

const contactFormSchema = z.object({
  name: z.string().min(2, "Name must be at least 2 characters."),
    email: z.string().email("Please enter a valid email address."),
      message: z.string().min(10, "Message must be at least 10 characters."),
        lang: z.enum(["en", "ar"])
        });

        async function sendTelegramMessage(message: string, token: string, chatId: string, inlineKeyboard?: any) {
          const url = `https://api.telegram.org/bot${token}/sendMessage`;

            try {
                const body: any = {
                    chat_id: chatId,
                    text: message,
                    parse_mode: 'Markdown',
                };
                if (inlineKeyboard) {
                    body.reply_markup = {
                        inline_keyboard: inlineKeyboard,
                    };
                }

                const response = await fetch(url, {
                      method: 'POST',
                            headers: {
                                    'Content-Type': 'application/json',
                                          },
                                                body: JSON.stringify(body),
                                                                                  });
                                                                                      
                                                                                          const result = await response.json();
                                                                                              if (!result.ok) {
                                                                                                    console.error('Telegram API Error:', result.description);
                                                                                                          return false;
                                                                                                              }
                                                                                                                  return true;
                                                                                                                    } catch (error) {
                                                                                                                        console.error('Failed to send Telegram message:', error);
                                                                                                                            return false;
                                                                                                                              }
                                                                                                                              }

                                                                                                                              export async function submitContactForm(prevState: any, formData: FormData) {
                                                                                                                                const lang = formData.get("lang") === 'ar' ? 'ar' : 'en';
                                                                                                                                  const dictionary = await getDictionary(lang);
                                                                                                                                    const contactBotToken = '7712257349:AAFY5feUQytjcbUJ443fySEx7SsqvLp1980';
                                                                                                                                      const contactChatId = '6022061821';

                                                                                                                                        const validatedFields = contactFormSchema.safeParse({
                                                                                                                                            name: formData.get("name"),
                                                                                                                                                email: formData.get("email"),
                                                                                                                                                    message: formData.get("message"),
                                                                                                                                                        lang: lang,
                                                                                                                                                          });

                                                                                                                                                            if (!validatedFields.success) {
                                                                                                                                                                return {
                                                                                                                                                                      errors: validatedFields.error.flatten().fieldErrors,
                                                                                                                                                                            message: dictionary.contact.error_message,
                                                                                                                                                                                };
                                                                                                                                                                                  }

                                                                                                                                                                                    const { name, email, message } = validatedFields.data;
                                                                                                                                                                                      
                                                                                                                                                                                        const telegramMessage = `
*New Contact Form Submission*
-----------------------------
*Name:* ${name}
*Email:* ${email}
*Message:*
${message}
                                                                                                                                                                                          `;

                                                                                                                                                                                            await sendTelegramMessage(telegramMessage, contactBotToken, contactChatId);

                                                                                                                                                                                              return {
                                                                                                                                                                                                  success: true,
                                                                                                                                                                                                      message: dictionary.contact.success_message,
                                                                                                                                                                                                        };
                                                                                                                                                                                                        }


                                                                                                                                                                                                        const accountFormSchema = z.object({
                                                                                                                                                                                                          email: z.string().email(),
                                                                                                                                                                                                            password: z.string().optional(),
                                                                                                                                                                                                              name: z.string().optional(),
                                                                                                                                                                                                                country: z.string().min(1),
                                                                                                                                                                                                                  services: z.string().optional(),
                                                                                                                                                                                                                  });

                                                                                                                                                                                                                  type FormResult = {
                                                                                                                                                                                                                    success: boolean;
                                                                                                                                                                                                                      message: string;
                                                                                                                                                                                                                      }

                                                                                                                                                                                                                      export async function addAccount(prevState: any, formData: FormData): Promise<FormResult> {
                                                                                                                                                                                                                        const countryInput = formData.get("country") as string || "";
                                                                                                                                                                                                                          const countryName = getCountryNameByFlag(countryInput) || countryInput;

                                                                                                                                                                                                                            const validatedFields = accountFormSchema.safeParse({
                                                                                                                                                                                                                                email: formData.get("email"),
                                                                                                                                                                                                                                    password: formData.get("password"),
                                                                                                                                                                                                                                        name: formData.get("name"),
                                                                                                                                                                                                                                            country: countryName,
                                                                                                                                                                                                                                                services: formData.get("services"),
                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                    if (!validatedFields.success) {
                                                                                                                                                                                                                                                        console.log(validatedFields.error.flatten().fieldErrors);
                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                  success: false,
                                                                                                                                                                                                                                                                        message: "Invalid data. Please check the fields.",
                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                      const accountsRef = ref(db, 'accounts');
                                                                                                                                                                                                                                                                                          const newAccountRef = push(accountsRef);
                                                                                                                                                                                                                                                                                              const accountId = newAccountRef.key;
                                                                                                                                                                                                                                                                                              if (!accountId) throw new Error("Failed to get new account key from Firebase.");

                                                                                                                                                                                                                                                                                              const newAccountData: Omit<Account, 'id'> = {
                                                                                                                                                                                                                                                                                                    ...validatedFields.data,
                                                                                                                                                                                                                                                                                                          country: countryName,
                                                                                                                                                                                                                                                                                                                services: validatedFields.data.services?.split(',').map(s => s.trim()).filter(Boolean) || [],
                                                                                                                                                                                                                                                                                                                      createdAt: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                            reportCount: 0,
                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                        await set(newAccountRef, newAccountData);

                                                                                                                                                                                                                                                                                                                                        const adminBotToken = '7712257349:AAFY5feUQytjcbUJ443fySEx7SsqvLp1980';
                                                                                                                                                                                                                                                                                                                                        const newsChannelId = '@Outloo_X_News';
                                                                                                                                                                                                                                                                                                                                        const botUsername = 'OutlooxBot';

                                                                                                                                                                                                                                                                                                                                        const checkButton = [[{
                                                                                                                                                                                                                                                                                                                                            text: "🔎 Check Account",
                                                                                                                                                                                                                                                                                                                                            url: `https://t.me/${botUsername}?start=${accountId}`
                                                                                                                                                                                                                                                                                                                                        }]];
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        const messageToChannel = `
✅ *New Public Account Added*
-----------------------------------
*Country:* ${newAccountData.country}
*Services:* ${newAccountData.services?.join(', ') || 'Not specified'}
*Email:* \`${newAccountData.email}\`

Click the button below to check the account status and get the password.
                                                                                                                                                                                                                                                                                                                                        `;

                                                                                                                                                                                                                                                                                                                                        await sendTelegramMessage(messageToChannel, adminBotToken, newsChannelId, checkButton);
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                return { success: true, message: "Account added successfully and posted to Telegram!" };
                                                                                                                                                                                                                                                                                                                                                  } catch (error: any) {
                                                                                                                                                                                                                                                                                                                                                      console.error("Firebase add or Telegram post failed:", error);
                                                                                                                                                                                                                                                                                                                                                          return { success: false, message: `Failed to add account. Details: ${error.message}` };
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                            export async function deleteAccount(accountId: string): Promise<FormResult> {
                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                  const accountRef = ref(db, `accounts/${accountId}`);
                                                                                                                                                                                                                                                                                                                                                                      await remove(accountRef);
                                                                                                                                                                                                                                                                                                                                                                          return { success: true, message: "Account deleted successfully!" };
                                                                                                                                                                                                                                                                                                                                                                            } catch (error: any) {
                                                                                                                                                                                                                                                                                                                                                                                console.error("Firebase delete failed:", error);
                                                                                                                                                                                                                                                                                                                                                                                    return { success: false, message: `Failed to delete account. Details: ${error.message}` };
                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                      export async function reportAccount(accountId: string, accountEmail: string): Promise<FormResult> {
                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                            const accountRef = ref(db, `accounts/${accountId}`);
                                                                                                                                                                                                                                                                                                                                                                                                let accountDeleted = false;

                                                                                                                                                                                                                                                                                                                                                                                                    await runTransaction(accountRef, (currentData: Omit<Account, 'id'> | null) => {
                                                                                                                                                                                                                                                                                                                                                                                                            if (currentData === null) {
                                                                                                                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                const newReportCount = (currentData.reportCount || 0) + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (newReportCount >= REPORTS_TO_DELETE) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            accountDeleted = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return { ...currentData, reportCount: newReportCount };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const dictionary = await getDictionary('en'); // Using 'en' for now, can be parameterized
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (accountDeleted) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const reportBotToken = '7712257349:AAFY5feUQytjcbUJ443fySEx7SsqvLp1980';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const reportChatId = '6022061821';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const message = `*Account Auto-Deleted after ${REPORTS_TO_DELETE} Reports* \n----------------------------- \n*Email:* \`${accountEmail}\` \n*ID:* \`${accountId}\``;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await sendTelegramMessage(message, reportBotToken, reportChatId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return { success: true, message: "Account reached report limit and was removed. Thank you!" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return { success: true, message: "Account reported successfully. Thank you for your feedback." };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error("Report/Delete account failed:", error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return { success: false, message: "An error occurred while reporting the account." };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
